Controllers/LinksController.cs
using LinkStorage.Models;
using LinkStorage.Services;
using LinkStorage.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LinkStorage.Controllers;

[Authorize]
public class LinksController : Controller
{
    private readonly ILinkService _service;
    private readonly IApiService _apiService;
    private readonly UserManager<User> _userManager;

    public LinksController(ILinkService service, IApiService apiService, UserManager<User> userManager)
    {
        _apiService = apiService;
        _userManager = userManager;
        _service = service;
    }

    [HttpGet]
    public async Task<IActionResult> Home()
    {
        var u = await _userManager.GetUserAsync(User);
        Guid.TryParse(u.Id ,out Guid uId);
        
        var links = await _service.AllTheLinksByUserId(uId);
        return View(links);
    }

    [HttpGet]
    [AllowAnonymous]
    /*
     * view all the public links or embed links
     */
    public async Task<IActionResult> Explore()
    {
        var content = await _service.GetPublicLinks();
        return View(content);
    }

    /*[HttpGet]
    public async Task<IActionResult> Detail(Guid? id)
    {
        var lnk = await _service.GetLinkById(id);
        

        return View();

    }*/

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(LinksCreateViewModel model)
    {
        if (ModelState.IsValid)
        {
            var u = await _userManager.GetUserAsync(User);
            var lnk = new Links
            {
                Link = model.Link,
                Site = model.Site,
                IsPublic = model.IsPublic,
                User = u,
                
                
            };
            lnk.User.Id = u.Id;
            if (lnk.IsPublic)
            {
                lnk.User.PublicPostCount++;
            }

            if (await _service.GetHtmlIfExist(model.Link) != null )
            {
                lnk.RawHtml = await _service.GetHtmlIfExist(model.Link);
            }
            else
            {
                var content = await _apiService.EmbededContent(model.Link);
                lnk.RawHtml = content.html;
            }
            
            await _service.CreateNewLink(lnk);
            return RedirectToAction("Home");
        }
        
        return View(model);
    }
}

Controllers/UsersController.cs
using LinkStorage.Models;
using LinkStorage.Services;
using LinkStorage.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LinkStorage.Controllers;

public class UsersController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly ILinkService _linkService;
    private readonly IFollowerService _followerService;

    public UsersController(UserManager<User> userManager, ILinkService linkService, IFollowerService followerService)
    {
        _userManager = userManager;
        _linkService = linkService;
        _followerService = followerService;
    }

    [HttpGet]
    public async Task<ActionResult> Profile(Guid? id, ProfileViewModel model)
    {
            var u = await _userManager.FindByIdAsync(id.ToString());
            var lnk = await _linkService.GetAllPublicLinksById(id);
            
            var CurrentUser = await _userManager.GetUserAsync(User);
            Guid CurrentUserGuidId = Guid.Parse(CurrentUser.Id);

            if (User.Identity.IsAuthenticated)
            {
                if (await _followerService.IsFollowing(CurrentUserGuidId, id))
                {
                    model.IsFollowing = true;
                }
                else
                {
                    model.IsFollowing = false;
                }
            }

            model.User = u;
            
            if (id == CurrentUserGuidId)
            {

                var allPostByUser = await _linkService.AllTheLinksByUserId(CurrentUserGuidId);
                model.links = allPostByUser;
                return View(model);
            }
            
            model.links = lnk;
            return View(model);

        
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LinkStorage</title>
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="bg-red-300  ">
        @{
            if (!User.IsInRole("Admin"))
            {
                <div class=" flex flex-row pt-4 pb-6">
                    <a class=" font-bold text-2xl ml-7 pl-1 flex border-l-2 border-red-900 flex-row justify-start" asp-area="" asp-controller="Home" asp-action="Index">LinkStorage</a>
                    <div class="">

                        <ul class=" flex flex-row justify-center  pl-8 ">
                            <li >
                                <a class=" font-semibold text-lg pl-3 text-red-900 hover:text-black " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li>
                                <a class=" text-lg pl-3  text-black hover:text-red-900" asp-area="" asp-controller="Links" asp-action="Explore">Explore</a>
                            </li>
                        </ul>
                    </div>

                    <div class="  flex flex-row justify-end pl-9 ">

                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <a class=" text-lg text-black hover:text-red-900 pl-3" asp-controller="Account" asp-action="Login"> Login </a>

                            <a class=" text-lg text-black hover:text-red-900 pl-3 " asp-controller="Account" asp-action="SignUp"> SignUp </a>

                        }
                        else
                        {
                            var userId = UserManager.GetUserId(User);
                            <a asp-controller="Users" asp-action="Profile" asp-route-id="@userId" class=" text-black border-b-2 text-lg font-bold border-black hover:border-red-900 hover:text-red-900 ">
                                Hello, @User?.Identity?.Name
                            </a>
                        }
                    </div>
                </div>
            }
            else
            {
            <div class=" flex flex-row pt-4 pb-6">
                <a class=" font-bold text-2xl ml-7 pl-1 flex border-l-2 border-red-900 flex-row justify-start" asp-area="" asp-controller="Home" asp-action="Index">LinkStorage</a>
                <div class="">

                    <ul class=" flex flex-row justify-center  pl-8 ">
                        <li>
                            <a class=" font-semibold text-lg pl-3 text-black " asp-controller="Admin" asp-action="ListUsers"> List User</a>
                        </li>
                        <li>
                            <a class=" font-semibold text-lg pl-3 text-black " asp-controller="Admin" asp-action="CreateRole"> Create Roles</a>
                        </li> 
                        <li class="flex flex-row  justify-end ">
                        <form method="post" asp-controller="Account" asp-action="LogOut">
                            <button type="submit">
                                <h3 class="font-semibold text-lg pl-3 text-black ">
                                   Log Out
                                </h3>
                            </button>
                        </form>
                        </li>
                    </ul>
                    
                </div>
            </div>
            }
        }
    </nav>

</header>
    <div class="container w-4/5 pt-20 flex justify-center">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

        
                

<footer class=" rounded-lg shadow m-4">
    <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
        <div class="sm:flex sm:items-center sm:justify-between">
            <a asp-controller="Home" asp-action="Index"  class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
                <span class="self-center text-black text-2xl font-semibold whitespace-nowrap ">LinkStorage</span>
            </a>
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
            {
                <form method="post" asp-controller="Account" asp-action="LogOut">
                    <button type="submit">
                        <h3 class="flex justify-end items-end  mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
                            <span class="inline-flex items-center px-3 py-2 text-sm font-medium text-center bg-red-300 hover:bg-red-900 hover:text-white text-black rounded-lg focus:ring-4 focus:outline-none focus:ring-red-300">Log Out</span>
                        </h3>
                    </button>
                </form>
            }
            <ul class="flex flex-wrap items-center mb-6 text-sm font-medium text-black sm:mb-0 ">
                <li>
                    <a asp-area=""  asp-action="About" asp-controller="Home" class=" hover:text-red-900 hover:underline me-4 md:me-6">About</a>
                </li>
                <li>
                    <a class=" text-black hover:text-red-900 hover:underline me-4 " asp-area="" asp-controller="Home" asp-action="Privacy" >Privacy Policy</a>
                </li>
                        
            </ul>
        </div>
        <hr class="my-6 border-black sm:mx-auto  lg:my-8" />
        <span class="block text-sm text-black  ">© 2024 <a asp-area="" asp-controller="Home" asp-action="Index" class="hover:underline">LinkStorage™</a>. All Rights Reserved.</span>
    </div>
</footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
    
    
    </body>
</html>