Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;

namespace LinkStorage.Models
{
    [Table("Users_Table")]
    public class User : IdentityUser
    {
        public long PublicPostCount { get; set; }
        public long FollowersCount { get; set; } 
        public long FollowingsCount { get; set; } 
        
        public ICollection<Links>? LinksCollection { get; } = new List<Links>();
        
        public virtual ICollection<Follows> Followers { get; set; }
        public virtual ICollection<Follows> Following { get; set; }
        
    }
}

ViewModels/ProfileViewModel.cs
using LinkStorage.Models;

namespace LinkStorage.ViewModels;

public class ProfileViewModel
{
    public IEnumerable<Links> links { get; set; }
    public User User { get; set; }
    // public string Following_id { get; set; }
    public bool IsFollowing { get; set; }
}

Controllers/FollowsController.cs
using LinkStorage.Models;
using LinkStorage.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LinkStorage.Controllers;

public class FollowsController : Controller
{
    private readonly IFollowerService _followerService;
    private readonly UserManager<User> _userManager;

    public FollowsController(IFollowerService followerService, 
        UserManager<User> userManager)
    {
        _followerService = followerService;
        _userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> FollowUser(Guid id)
    {
        if (!User.Identity.IsAuthenticated)
        {
            return RedirectToAction("Login", "Account");
        }

        var targetId = id;
        
        var currentUser = await _userManager.GetUserAsync(User);
        var targetUser = await _userManager.FindByIdAsync(targetId.ToString());
        Guid currentUserIDGuid = Guid.Parse(currentUser.Id);

        try
        {
            targetUser.FollowersCount++;
            currentUser.FollowingsCount++;
            
            await _followerService.FollowNewUser(currentUserIDGuid, targetId);
            
            
            return RedirectToAction("Profile", "Users", new { id = targetId });
        }
        catch (Exception e)
        {
            ModelState.AddModelError("", "An error occurred while following the user.");
            return RedirectToAction("Profile", "Users", new { id = targetId });
        }
        
        
    }
    
    [HttpGet]
    public async Task<IActionResult> UnFollow(Guid id)
    {
        if (!User.Identity.IsAuthenticated)
        {
            return RedirectToAction("Login", "Account");
        }

        var targetId = id;
        
        var currentUser = await _userManager.GetUserAsync(User);
        var targetUser = await _userManager.FindByIdAsync(targetId.ToString());
        Guid currentUserIDGuid = Guid.Parse(currentUser.Id);

        try
        {
            if (await _followerService.IsFollowing(currentUserIDGuid, targetId))
            {
                targetUser.FollowersCount--;
                currentUser.FollowingsCount--;
            
                await _followerService.UnFollow(currentUserIDGuid, targetId);
            
            
                return RedirectToAction("Profile", "Users", new { id = targetId });
            }
            
        }
        catch (Exception e)
        {
            ModelState.AddModelError("", "An error occurred while Unfollowing the user.");
            return RedirectToAction("Profile", "Users", new { id = targetId });
        }
        
        return RedirectToAction("Profile", "Users", new { id = targetId });
    }
    
}

Controllers/LinksController.cs
using LinkStorage.Models;
using LinkStorage.Services;
using LinkStorage.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LinkStorage.Controllers;

[Authorize]
public class LinksController : Controller
{
    private readonly ILinkService _service;
    private readonly IApiService _apiService;
    private readonly UserManager<User> _userManager;

    public LinksController(ILinkService service, IApiService apiService, UserManager<User> userManager)
    {
        _apiService = apiService;
        _userManager = userManager;
        _service = service;
    }

    [HttpGet]
    public async Task<IActionResult> Home()
    {
        var u = await _userManager.GetUserAsync(User);
        Guid.TryParse(u.Id ,out Guid uId);
        
        var links = await _service.AllTheLinksByUserId(uId);
        return View(links);
    }

    [HttpGet]
    [AllowAnonymous]
    /*
     * view all the public links or embed links
     */
    public async Task<IActionResult> Explore()
    {
        var content = await _service.GetPublicLinks();
        return View(content);
    }

    /*[HttpGet]
    public async Task<IActionResult> Detail(Guid? id)
    {
        var lnk = await _service.GetLinkById(id);
        

        return View();

    }*/

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(LinksCreateViewModel model)
    {
        if (ModelState.IsValid)
        {
            var u = await _userManager.GetUserAsync(User);
            var lnk = new Links
            {
                Link = model.Link,
                Site = model.Site,
                IsPublic = model.IsPublic,
                User = u,
                
                
            };
            lnk.User.Id = u.Id;
            if (lnk.IsPublic)
            {
                lnk.User.PublicPostCount++;
            }

            if (await _service.GetHtmlIfExist(model.Link) != null )
            {
                lnk.RawHtml = await _service.GetHtmlIfExist(model.Link);
            }
            else
            {
                var content = await _apiService.EmbededContent(model.Link);
                lnk.RawHtml = content.html;
            }
            
            await _service.CreateNewLink(lnk);
            return RedirectToAction("Home");
        }
        
        return View(model);
    }
}

Controllers/UsersController.cs
using LinkStorage.Models;
using LinkStorage.Services;
using LinkStorage.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LinkStorage.Controllers;

public class UsersController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly ILinkService _linkService;
    private readonly IFollowerService _followerService;

    public UsersController(UserManager<User> userManager, ILinkService linkService, IFollowerService followerService)
    {
        _userManager = userManager;
        _linkService = linkService;
        _followerService = followerService;
    }

    [HttpGet]
    public async Task<ActionResult> Profile(Guid? id, ProfileViewModel model)
    {
            var u = await _userManager.FindByIdAsync(id.ToString());
            var lnk = await _linkService.GetAllPublicLinksById(id);
            
            var CurrentUser = await _userManager.GetUserAsync(User);
            Guid CurrentUserGuidId = Guid.Parse(CurrentUser.Id);

            if (User.Identity.IsAuthenticated)
            {
                if (await _followerService.IsFollowing(CurrentUserGuidId, id))
                {
                    model.IsFollowing = true;
                }
                else
                {
                    model.IsFollowing = false;
                }
            }

            model.User = u;
            
            if (id == CurrentUserGuidId)
            {

                var allPostByUser = await _linkService.AllTheLinksByUserId(CurrentUserGuidId);
                model.links = allPostByUser;
                return View(model);
            }
            
            model.links = lnk;
            return View(model);

        
    }
}

Views/Users/Profile.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManager
@model LinkStorage.ViewModels.ProfileViewModel
@{
    
    ViewData["Title"] =  "Profile ";
}
<div>
    <div class="ml-24">
        <h1 class=" flex flex-row justify-center text-5xl text-red-900 border-b-2 border-black pb-4 "> @Model.User.UserName </h1>
        
        <div class="flex flex-row content-evenly p-5 space-x-5  ">
            <p> Post : @Model.User.PublicPostCount</p>
            <p> Followers : @Model.User.FollowersCount</p>
            <p>Following : @Model.User.FollowingsCount</p>
        </div>
        
         
        
        @if (User.Identity.IsAuthenticated)
        {
            if (Model.User.Id != UserManager.GetUserId(User))
            {
                if (Model.IsFollowing)
                {
                    <form method="get">
                        <button>
                            <a class="inline-flex items-center px-3 py-2 text-sm font-medium text-center bg-red-300 hover:bg-red-900 hover:text-white text-black rounded-lg focus:ring-4 focus:outline-none focus:ring-red-300" asp-controller="Follows" asp-action="UnFollow" asp-route-id="@Model.User.Id">Un Follow</a>
                        </button>
                        
                    </form>
                }
                else
                {
                    <form method="get">
                        <button> <a  class="inline-flex items-center px-3 py-2 text-sm font-medium text-center bg-red-300 hover:bg-red-900 hover:text-white text-black rounded-lg focus:ring-4 focus:outline-none focus:ring-red-300" asp-controller="Follows" asp-action="FollowUser" asp-route-id="@Model.User.Id">Follow</a> </button>
                    </form>

                }
                
                <br/>
                <hr/>
            }
            else
            {
                <button> <a  class="inline-flex items-center mb-6 px-3 py-2 text-sm font-medium text-center bg-red-300 hover:bg-red-900 hover:text-white text-black rounded-lg focus:ring-4 focus:outline-none focus:ring-red-300" asp-controller="Links" asp-action="Create">Upload New Link</a> </button>
                <br/>
                <hr/>
            }
            

           
        }
        
        
    </div>
    <div>
        @if (Model.User.Id != UserManager.GetUserId(User))
        {
            @foreach (var value in Model.links)
            {
                <div class=" ml-36 w-8/12  rounded-lg shadow ">
                    <div class="rounded-t-lg">
                        @Html.Raw(@value.RawHtml)
                    </div>
                    <div class="p-5">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">Posted By : @value.User.UserName</h5>
                        <p class="mb-3 font-normal text-gray-700 "> Site : @value.Site</p>
                        <a href="@value.Link" target="_blank" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center bg-red-300 hover:bg-red-900 hover:text-white text-black rounded-lg focus:ring-4 focus:outline-none focus:ring-red-300">
                            View Post
                            <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                            </svg>
                        </a>
                    </div>
                    <hr class="w-48 h-1 mx-auto my-4 bg-red-900 border-0 rounded md:my-10 ">
                </div>
            }

        }
        else
        {
            foreach (var values in Model.links)
            {
                <div class=" ml-36 w-8/12  rounded-lg shadow ">
                    <div class="rounded-t-lg">
                        @Html.Raw(values.RawHtml)
                    </div>
                    <div class="p-5">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 ">Is It Public :
                            @if (values.IsPublic)
                            {
                                <h5 class="text-2xl font-bold tracking-tight text-gray-900 ">Yes</h5>
                            }
                            else
                            {
                                <h5 class="text-2xl font-bold tracking-tight text-gray-900 ">No</h5>
                            }
                        </h5>
                        <h6 class="mb-3 font-normal text-gray-700 "> Site : @values.Site</h6>
                    </div>
                    <hr class="w-48 h-1 mx-auto my-4 bg-red-900 border-0 rounded md:my-10 ">
                </div>

            }
        }
    </div>



</div>

    
    